### ISSUE TITLE
Build model

### ISSUE THREAD

**Issue by omkarmoghe** [omkarmoghe/Pokemap#11]
Build basic object models for Pokemon, gyms, etc.

Example models exist in the main Python repo, all we have to do is translate them to Java.

**Comment by ryangardner** [comment]
see https://github.com/Grover-c13/PokeGOAPI-Java

**Comment by omkarmoghe** [comment]
Interesting. We're doing all the auth stuff already without having to use interceptors by just disabling redirects. Might be worth migrating the models and stuff over, though.

**Comment by comann** [comment]
I could help with translating over from python. I am not to familar with python. Are the models from the proto files or are there python model classes?

**Comment by omkarmoghe** [comment]
@comann Yeee. So the `.proto` files are used for the network requests and getting data from their servers. Once we get that data we want to create model objects in Java. Check out the link @ryangardner posted above - it contains some Java models already. See if you can look into bringing those over into this app. Also checkout the main python repo (link in Readme). They created some models as well which might be a lot easier to read/understand and translate over.

**Comment by crckdns** [comment]
.proto ...stands for procotol. It's just the "class" for the communication done between the points (server-client) - that simply explained what the .proto files are 🔨

**Comment by comann** [comment]
@omkarmoghe  @ryangardner  I have reviewed the PokeGOAPI-Java the class structure is well defined. All there classes are have a protobuf(s) encapsulated. Generating the protobufs for the entire existing api might help us out, but more modular rather than one single PokemonOuterClass. It might make the code clearer if we were to model the proto objects after this [reddit thread](https://www.reddit.com/r/pokemongodev/comments/4svl1o/guide_to_pokemon_go_server_responses/). Then provide the model classes to help abstract out the protobuf classes.  They are too bulky and confusing to use for people who are not familiar with them.

**Comment by omkarmoghe** [comment]
@comann agreed. good idea!

**Comment by comann** [comment]
I think this can be closed now.
