### ISSUE TITLE
Service & Notification

### ISSUE THREAD

**Issue by vidarr101** [omkarmoghe/Pokemap#112]
Feature request

Settings
-Enable PokeService

PokeService
On going into the background a on going notification starts that polls your area and your area with a user defined radius at a user defined refresh period.  The notification states how many pokemon are in the radius and how many distance units it is to each one.   

Example
4 Pokemon in 1 mile radius; 0.5mi to ratata, 0.25 mi to pidgeo, 0.10 miles to bulbasaur...

Benefits:
Not everyone has 2 devices to use and also switching back and forth between the app would be a pain :-)
Plus if this is done right the notification could be displayed on a wearable.

**Comment by vidarr101** [comment]
I can take a look at starting a rough draft of this

**Comment by s7092910** [comment]
I might leave out the distance to unit.

**Comment by ManojMadanmohan** [comment]
This sounds like a good idea. This would work well if the user is stationary at one place or walking around.

One related use case I could think of, in addition to this, we can have something "travelling mode" as well, when the user is travelling by a vehicle. Instead of polling the current location, we can determine the user's potential location 2 minutes in the future, check the pokemon available over there and give a notification saying "1 Pokemon coming up in 2 minutes".

The user can simply turn this on when he's travelling, get notified of upcoming pokemon on his route via a notification, and simply start the app and catch pokemon on his way as he travels.  

I personally don't like travelling around just to catch pokemon, and usually use the app during commute from/to office or somewhere else. There might be others like me with the same use case. With this, users won't have to keep the app opened to check continuously; instead he just gets notified whenever theres a pokemon coming up on his way.

**Comment by rohanjain1** [comment]
Implemented.
