### ISSUE TITLE
PTC login failed after each app restart

### ISSUE THREAD

**Issue by cwizard** [omkarmoghe/Pokemap#225]
PTC login failed after each app restart, I can log in manually.

**Comment by jLynx** [comment]
Same here, before all these updates if it failed it would keep my username and password in the boxes and I could just hit login without needing to retype all the details. So somone needs to add that back in

**Comment by Giggitybyte** [comment]
Could be happening because of @s7092910's recent [commit](https://github.com/omkarmoghe/Pokemap/commit/4687b99c953481a2cda267e765efb305ba4e5807)?

**Comment by s7092910** [comment]
Yeah it was something that I did in my recent commit. I'll be fixing it in a bit.

**Comment by s7092910** [comment]
PR is up, just waiting for it to be approved.

**Comment by Kraker01** [comment]
I'm unable to login with PTC account ("PTC Login failed") even if I can login with desktop map

**Comment by quinnj** [comment]
Even if I go to the PTC website, it's showing some kind of "global downtime" it seems like; I can't login or see anything and just get a message about how things are overloaded at the moment. I'm thinking that's why I'm seeing the consistent PTC login failures this morning.

https://www.pokemon.com/us/pokemon-trainer-club/

**Comment by comann** [comment]
Merged and Fix.
