### ISSUE TITLE
apk freezes if it was running in the background for a while

### ISSUE THREAD

**Issue by maxkadur** [omkarmoghe/Pokemap#270]
If Pokemap was running in the background for a while and i try to scan manually, nothing happens. The only way to fix this, is to restart the app. Are there more people who have this problem?

**Comment by Sn3akySl0th** [comment]
I'm having the same issue. It just makes it like it is searching in my
current area but doesn't find any Pokemon. Very annoying.

**Comment by ottnorml** [comment]
Same by me. :(

**Comment by tanishbaansal** [comment]
Same here .. please someone find a solution for this

**Comment by s7092910** [comment]
Note to whoever is possibly looking at this. It might be that the AuthInfo expires.

**Comment by comann** [comment]
Able to replicate as well. Bumping this up to 0.1. Pretty important for first feature set.

**Comment by tanishbaansal** [comment]
I search for pokemon and then catch it in pokemon go app but when I load the app from the opened app screen amd long press to search nothing happens and I have to restart the app ..

**Comment by omkarmoghe** [comment]
it's a feature so that you guys stop playing Pokemon Go all the time and be productive :smile: 

in all seriousness though we are looking into this

**Comment by kyr0** [comment]
Looks like the service start/stop logic is wrong or I don't get it

a) Starts every time MainActivity onCreate()
b) Starts every time onPause() when !skipNotificationServer
    b1) Side note: And thus, we start the service, when the user switches to the SettingsActivity...
c) Stops every time onResume() 
d) And when theme is changed, we call recreate() in MainActivity so it starts the service again one more time because of  a)

There is nowhere a check for how many instances are actually running?!

Can someone fix that please who has a clue how this should work? :))

**Comment by Nicolai0685** [comment]
i put a breakpoint in getCatchablePokemon() in NianticManager.java to see what happens when you search for pokemon after you pause and resume the app. it seams that mPokemonGo is null, and therefore the entire search is not executed.
