### ISSUE TITLE
Installing Application over old install

### ISSUE THREAD

**Issue by ghost** [omkarmoghe/Pokemap#277]
Alright, this probably sounds gimmicky but would it be possible to simply install the new builds on top of the old installs to remove the extra step of uninstalling the app and reinstalling it?

**Comment by s7092910** [comment]
Currently we are doing developer builds. Since the developer builds all share the same version code this happens. We will be doing milestone builds every so often. Those milestone builds will have different version codes. This will allow going from 1 milestone build to another to be installed on top of the other. Same with going from a milestone build to a developer build.

But going from dev build to dev build you will have to reinstall.

**Comment by ghost** [comment]
Would it be possible to make the version number as V1.0 PR.396 or would that be too much trouble for basically nothing?

**Comment by s7092910** [comment]
It would be a bit too much trouble. As automating something like that is extremely difficult.

**Comment by ghost** [comment]
Alright, thanks for the quick replies. You rock! :)
