### ISSUE TITLE
Question: Pokehound

### ISSUE THREAD

**Issue by Sn3akySl0th** [omkarmoghe/Pokemap#283]
Anyone familiar with Pokehound? They claim to be able to get more Pokemon than anyone else. Do you know if they are legit and wouldn't the same info be available to us through this app given some time?
Or may they be doing something that is outside the scope of this project? They want $4.99 a week and don't even have an amazing app like this.
https://pokehound.com/#/

**Comment by socrates2510** [comment]
Scam. You'll do better with the python project deployed in Heroku. With your own fake account. It passed me off to see this showing up.

**Comment by s7092910** [comment]
Yes the same info that they can get, we can get. On top of that, their app is using a webview pretty much.

**Comment by Sn3akySl0th** [comment]
Are spawn locations and times available so that we know when and where specific Pokemon will be available or is it random?

**Comment by s7092910** [comment]
Yes we have that, they are included in the current app.

**Comment by ghost** [comment]
Clefebvre81, We can't predict where pokemons WILL spawn, we'd have to hack into Niantic servers to do that for all I know, however we CAN know when they will disappear. Correct me if I'm wrong, s7092910.

**Comment by s7092910** [comment]
@Lionir Areas around the world are populated by pokemon spawns. So that means a spawn has location in the real world, it doesn't move. At a certain time every hour, it will spawn a pokemon based on a list of possible pokemon and the weight to spawn them. So we do have access to the spawn locations, we don't show them because that is probably not what you are after. We only show the pokemon that have spawned and are able to be caught at the time of the scan. We do know when they disappear, which is why we have a countdown timer.

**Comment by ghost** [comment]
@s7092910 Ah, I see. I meant that we can't predict which Pokemons will appear at a said time, can we? We can obviously know spawn points but not which Pokemon will appear, correct?

**Comment by s7092910** [comment]
@Lionir That is correct, we don't know which Pokemon will appear at a spawn. Maybe with enough data points you could determine the weights for choosing which pokemon.

**Comment by ghost** [comment]
@s7092910 Well, that is unless it's completely randomised from a list of specific pokemons. Anyhow, thanks for the clarification.

**Comment by Sn3akySl0th** [comment]
Thank you for the great explanation. I didn't know if certain Pokemon spawn in the same location at specific times or not. That explains why I don't see the same Pokemon at work every day.
