### ISSUE TITLE
Scanning algorithm is broken

### ISSUE THREAD

**Issue by mihailivanchev** [omkarmoghe/Pokemap#329]
Latest version of the code has it's scanning algorithm broken. Scanning steps (or circles) don't touch, and after first step, appear at random spots. Also, initial location of the touch is not scanned.

**Comment by s7092910** [comment]
This is because the Pokemon Go servers have been having issues for the last day. Quite a lot of the responses from the server end up just being blank. So to combat this, we have slowed down the search a fair amount.

**Comment by mihailivanchev** [comment]
Speed is OK. Problem is in the scanning pattern. Here, take a look.  Build from the most current files on Github (as of writing this, it's been done 10 minutes ago)
![screenshot_20160729-105156](https://cloud.githubusercontent.com/assets/2547040/17241545/eb786826-557a-11e6-9c0e-093d6a299fcd.png)

**Comment by Krystev** [comment]
I have the same problem with the scanning.

**Comment by s7092910** [comment]
What I mean is that if we send requests to the server to quickly, some of the requests get rejected and sent back with no data in them. 

Currently we do not rescan a spot if it fails getting data.

To allow the requests to have enough time between them, you do not get the requests rejected from the server. We have a Pull request that is going to be increasing the time between requests.

But the reason why this is happening is because of something out of our reach as it is an issue with the PokemonGo servers. We are already doing what we can. The algorithm might seem broken, it isn't.

**Comment by mihailivanchev** [comment]
Ok, thanks. Keep up the good work

**Comment by DoraKlikOpDora** [comment]
No, this is not an issue with the PoGo servers, PoGo blocked us by restricting the time between each request. They throttle requests.

**Comment by s7092910** [comment]
That is just a theory. The server stability issue in the last 36h were most likely due to a DDoS. Which the help solve that is have the server send back responses that are empty if requested within a given time period.

**Comment by DoraKlikOpDora** [comment]
Since this limit is set on an account, not on an IP it would not be because of a DDoS.
