### ISSUE TITLE
Lured Pokemon Don't Appear

### ISSUE THREAD

**Issue by blastagator** [omkarmoghe/Pokemap#348]
Lured pokemon do not appear on the map, even though the option is enabled.

**Comment by s7092910** [comment]
They do appear on the map. As I told you they don't look any different from others. In #360 I have added in a Lured tag when you click on a pokemon if it is a lured pokemon.

Also note that Lured Pokemon are only pokemon that spawn due to a Lure Module on being placed on a pokestop. Incense pokemon do not count as lured pokemon and are only visible to the people who are using the incense.

One thing you can do is put your search steps to 1. Search near an area that you know has lures on the pokestops. You will notice that there are pokemon that will appear outside your search area. Those are the lured pokemon.

**Comment by PutterPlace** [comment]
I'll agree with blastagator on this one. They don't always show. Here is a pic of Pokemap and a screenshot from the game of the exact same location:

http://imgur.com/Q8sZvXh
http://imgur.com/KSnp78R

To add to that, the two pokestops in this area are also not shown on the map, though the option is enabled in the settings. Could that be what's causing the problem?

**Comment by PutterPlace** [comment]
I forgot to mention my point about the lured pokemon: there was a lured staryu, as you can see in-game, but it wasn't showing on the map.

**Comment by s7092910** [comment]
@FatThing That has to do with the issue we have of Niantic recently changing a bit of how the API behaves. Which effects much of our scanning behavior. So right now lured pokemon and pokestops do not show up.

**Comment by PutterPlace** [comment]
@s7092910 Ah ok. That makes sense. I've got a slight bit of experience with protobuf, so maybe I could give it a look soon if it's not figured out before then. :-P

**Comment by s7092910** [comment]
@FatThing Thanks for the offer. But the main team is talking about the future of this project right now. So I believe we will be laying off on any major updates for now. But for now if you want a simple fix, just go into the Niantic Manager and then change the one of the Thread.sleep(133) in each method that has it to 5000 or above. 5000 is the minimum tho.

**Comment by PutterPlace** [comment]
@s7092910 I'm honestly not too worried about it. I can live with it how it is for now.
