### ISSUE TITLE
None pokemon appeared 

### ISSUE THREAD

**Issue by Xelwon** [omkarmoghe/Pokemap#377]
When you pick up for search nothing appears
But in background sevice yes ( used to the searches time is 60 seconds)
 I read that on new pokemon go version only is possible do searchs to server every 5 seconds. So is needed an option to change it manualty in the app on foreground too. May be that it becomes change so is better to can change it.

**Comment by s7092910** [comment]
Niantic has changed the backend quite a bit to make it harder for mappers to work. We are currently looking at some solutions to give you the same type of performance as we had before.

**Comment by heomap14** [comment]
Niantic putting a throttle bot. a request for scan can only be per 5s.. so if we change the scan interval to that, 90% pokemon will pop up. or that what they said over at the AAA thread

**Comment by blastagator** [comment]
People got greedy.  https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2774
"I haven't been banned and I'm running 60 workers with 60 accounts"

Come on people!

**Comment by s7092910** [comment]
@heomap14 We do know that. We are trying to setup certain things so that it will be faster and easier for us to adapt to changes like this or the app even does the adapting for you.

**Comment by hhagmans** [comment]
Is it possible to quickfix this?
I haven't really looked at the code, but is there a variable to set the requests to one per 5s?
I would do that myself until you have found a better solution.

**Comment by Xelwon** [comment]
I like that idea, Set requests to servers one each five seconds on source code.

**Comment by Kazpers** [comment]
I'd like that too. I'm trying to set it myself in the code, but while I'm a developer it's not for Android, so it's slow going trying to track this down ( and testing means building, transferring and installing the apk, since I have no debug environment set up). A pointer on what lines to change manually until a better solution is built would be highly appreciated...

While it'd tank performance it'd at least show some pokemons at a time when zero solutions for this currently work (and the in-game tracking - limited as it was - has been removed as well). Perhaps scan a smaller area to compensate for now.

**Comment by hhagmans** [comment]
I have looked at the code for a few minutes..

Maybe the occurences of "133" in this file (https://github.com/omkarmoghe/Pokemap/blob/dev/app/src/main/java/com/omkarmoghe/pokemap/controllers/net/NianticManager.java) are timeouts for the Niantic Service? I can't test it right now as I'm not at home.

**Comment by Kazpers** [comment]
I think you're right (damn magic numbers). I pulled it out into it's own property and set it to 3000 instead - since it runs thread.sleep twice each time I'm guessing that gives 6 seconds between each scan. Quick testing after building seems to confirm this. It's very slow - performance it horrible, but it'll show you some pokemons it seems...

Edit: It seems I spoke too fast. It finished a ring of searches around my position finding 4 pokemons and then stopped. Must be some other calls being made that triggers Niantics throttler?

**Comment by hhagmans** [comment]
Ok, I have also tested it with a timeout of 2500 and it seems to work for me. I could do multiple searches and it seems the found pokemon are correct (I only did like 3 searches, so that needs more tests). But it's of course incredibly slow. I'll wait for a better fix and until then I'll keep my current fix. It's at least ok if I want to find a pokemon from the nearby list.

**Comment by kaloczidev** [comment]
I've set the sleep to 1330, now it works fine but slow.

**Comment by comann** [comment]
Duplicate. https://github.com/omkarmoghe/Pokemap/issues/383
