### ISSUE TITLE
Map can use mysql 

### ISSUE THREAD

**Issue by simoher** [omkarmoghe/Pokemap#390]
Use db so users using map can see pokemons scanned by other users. That way we can easily spread the load to multiple users. Maybe  androod users could take some of that load when the are not scanning thir own location.

**Comment by s7092910** [comment]
We won't be doing that, because it requires a server or service inbetween everything and those are not exactly free. On top of that, it will use up more data on the phone.

The core team plans to have this be a nice and sturdy app.

**Comment by ghost** [comment]
@s7092910 The main thing about this app is that it's not dependent on any server or service. That's why I've chosen it over Pokevision and such services. Their servers just crash so much and it becomes a royal pain to do anything. Thank you for using your own code and no outside server or service. :)
