### ISSUE TITLE
[Suggestion] Use PokeGOAPI auth system instead of custom one

### ISSUE THREAD

**Issue by loicortola** [omkarmoghe/Pokemap#391]
Hello guys,

first thanks for the awesome work and efforts you are putting on this app.
Looking at the code, I found that the whole login system had been homemade.
The PokeGO API has really put some efforts into making a more simple, well-integrated login system.
I think there is no use in trying to maintain this twice.

Would you take a Pull Request with a refactoring allowing the Auth API to be compliant with PokeGO API?
This would also allow to take the latest PokeGO APIs and fixes.

Best wishes,

Loïc

**Comment by s7092910** [comment]
We decided to go with our own implementation because at the time our implementation was better and still is because it allows us better access to actually knowing what is going wrong in the login process. On top of that, in the past few days we actually had a working fix for the google login well before PokeGO API did, they ended up looking at how we fixed the google login to fix theirs.

It is very much a trade off between hey we don't have to write code at the cost of have to wait till they fix something. While on the other hand, we can have more control over the login process and give more feed back to the users when logging in and something goes wrong at the cost of us having to write the code and fix it when something happens.

In proper UI, you must give user proper feedback when something goes wrong. That is what separates between good programs and bad programs. If we were using the PokeGo API login, we wouldn't have found out that if your PTC account is not activated you can't use it for Pokemon Go. 

We even talked about it as a team and decided it was best to go with our own implementation.

**Comment by loicortola** [comment]
I see your point, even though I try to keep faith in humanity and think it could have been fixed by doing a pull request to PokeGO API instead of looking the other way and reimplementing everything on your side... 
(What? Contributing to other opensource projects? Doesn't that sound silly? Typical example of not caring about things we rely on. Is this the team spirit in this project?)

I understand the need for flexibility though, and totally agree from the fact that the Exception Handling could be better on the PokeGO API for both registration and authentication, which I am currently trying to improve (by raising more thorough exceptions).
I also think that proper App development requires good APIs and loose coupling for proper maintability, and doing registration and authentication two times on two levels (from your side for login, then to PoeGO API for requests) goes against those best practices.

Thanks for your feedback, I assume that if it is a team decision, it won't be questionable, and you wont need a pull request with the new version then.

Again, bravo for the awesome work, and let me know if I could help any other way.

Loïc
