### ISSUE TITLE
Question: Development

### ISSUE THREAD

**Issue by Sn3akySl0th** [omkarmoghe/Pokemap#397]
Just curious if development on this has stopped or if people are looking at a way around Niantic and their stupid throttle? I don't want to quit playing but it is impossible to find good Pokémon in the current state of the game.

**Comment by mastescarhead1** [comment]
Devs are looking for an alternative. They have one, but they don't want to release it until it's fully functional.
Like you, I prefer to know the progress, but it's up to the devs if they want to reveal

**Comment by ghost** [comment]
@clefebvre81 @mastescarhead1 There are currently alternatives which work but I definitely think this project is superior in various aspects. Just google it and you're bound to find something. I won't name any because I have huge respect for the developers of this project.

**Comment by mastescarhead1** [comment]
^ Oh I know there are projects that are currently semi functional, but I agree with @Lionir , this project is definitely superior. Hence why I'm sticking around to find out what else the app will have :)

**Comment by CarstenHouweling** [comment]
I'm still improving the navigation module so I have high hopes for this project.

**Comment by ghost** [comment]
@CarstenHouweling You could take inspiration from the PokeScanner code since they have a working navigation system using Google maps. Well, unless you wanted to not use Google Maps.

@Mastescarhead1 Semi-functional, I'd say that some have very nice features (more than functional) which could be implemented here but this has the best features overall, very nice UI and no ads to top it off. I really hope for multi-account support for faster scans and more information about the gyms. This is all I'd ever dream for, and well, that they are able to make the scanning work since I've been eagerly waiting for that update.

**Comment by CarstenHouweling** [comment]
@Lionir Opening an Intent to Google Maps is simply childsplay

**Comment by ghost** [comment]
@CarstenHouweling Well, it's surely easy but you could implement it while you're putting more time into your version which would replace it once finished.

**Comment by CarstenHouweling** [comment]
@Lionir There have already been two working versions... Improvements just make it nicer.

**Comment by jLynx** [comment]
https://plus.google.com/+pokemongo/posts/ZyNnoczdRFt

**Comment by ghost** [comment]
@CarstenHouweling Well, yeah, I've just never got to try it since they weren't included in the builds.

**Comment by ghost** [comment]
@DarkN3ss61 Their justifications are mediocre. They are killing their own users. Good luck finding any pokemons without any indication of where they are, you'll be walking and walking until they disappear or they were never even there in the first place. The current state of the game is totally unacceptable and broken.

**Comment by rohanjain1** [comment]
Hey guys,
Good to hear you like the work, we're not gonna abandon the project for sure.
There will be an official announcement about the future of this project soon.

**Comment by kitohiro** [comment]
hello,  are you still working to find a fix or you gave up this app ?

**Comment by hhagmans** [comment]
I think they are either waiting for a fix for the current api from others or are actively working on the problem with others. Either way, a fix for the problem is not trivial and many devs are working on it (a link to a reddit thread has been posted in another issue), so it will take some time.
I'm sure we will see updates of this app when the API is working again. Until then we have to wait.

**Comment by comann** [comment]
We have been working diligently and have an upcoming release soon.
