### ISSUE TITLE
pgoapi error

### ISSUE THREAD

**Issue by xratablancax** [omkarmoghe/Pokemap#414]
I get the following :( not sure what im doing wrong

Error [Error 2] The system cannot find the file specified while executing command git clone -q https://github.com/keyphact/pgoapi.git c:\users<user>\appdata\local\temp\pip-build-ngfsts\pgoapi
Cannot find command 'git'

**Comment by s7092910** [comment]
A) This because you don't have git installed and B) the issues here are only things related to the android app for this repo. Not for what I believe is the python map. C) Issues here are also only for the official app from this repo. So any custom modifications that cause issues that are not in the repo itself are not supported and will not be fixed by the team.

**Comment by xratablancax** [comment]
I apologize, didnt even know there was an app for pokemap, can you provide
me with a link for instructions on how to install it? or an apk?

**Comment by s7092910** [comment]
The App itself has gone closed source. We will be making a release of the apk soon. It will be in the release page for this repo.

**Comment by xratablancax** [comment]
sweet!

not to ask to much but, any prototype i could test a while.. for some
reason other scanners don't pick up anything in the small town i live in,
except for the windows version of pokemap... go radar from IOS picks up
stuff from bigger cities but not my hometown... :/

On Wed, Aug 10, 2016 at 10:27 PM, Christopher Beda <notifications@github.com

**Comment by blackmaskmen** [comment]
Guys you all doing great job!! Let us all know if there is a apk ready!!
