### ISSUE TITLE
Not Showing Pokemon.

### ISSUE THREAD

**Issue by TheAussie** [omkarmoghe/Pokemap#420]
The App doesn't seem to be showing any nearby pokemon.

**Comment by Anu6is** [comment]
It's very disheartening to know that there are so many person who are aware of GitHub, can find these open source projects and are technical enough (it doesn't take that much, but still) to install an apk on their Android devices. Yet these same persons don't seem to have basic understanding of forum etiquette. 
- Search previous posts/issues before creating a new one.
- Read any relevant notes created by the admins/developers.

If you aren't contributing to the development of the project, at least try not to contribute to the spam either.

**Comment by TheAussie** [comment]
"Contribute to spam", hmph.. so you're suggesting there is multiple posts of the same thing for a 9 day ago release of the apk? regarding no pokemon showing?

**Comment by Anu6is** [comment]
That is exactly what I am suggesting. 
Thankfully the majority of them have been closed. 

Any issue raised that speaks to something in the app not working right now is spam. If you were to read the "Read Me" (https://github.com/omkarmoghe/Pokemap/blob/dev/README.md) provided by the developers, you would know that there is no working version of the app hosted here at this time. Ever since the API change that stopped all mapping apps from working, this app has not been updated officially. Whatever you have downloaded currently is an outdated version that uses the old API, meaning IT DOES NOT WORK. 

So again, reporting issues for an obsolete app equates to spam. You should really take caution to inform yourself about the software that you are installing on your device. Especially software that is side loaded, bypassing some of the security that your device provides.

**Comment by TheAussie** [comment]
Fair enough, sorry for "Contributing to spam", i have nothing further to add to this pointless post.

**Comment by skryptus** [comment]
To start, this is not a "Forum" per se, but an Issue Tracker. And, while I agree with @Anu6is' suggestions of reading the previous Issues and notes from the developers, I don't think his way of answering is in the least bit productive - on the contrary, its agressiveness probably disencouraged @TheAussie, and maybe other readers, from contributing to this project.
It's better to clarify than simply to scold.

To be clear, the only thing the ReadMe says is not currently hosted here is the current version of the project, which has been moved to a private repository. It does, however, mention the releases would be uploaded periodically, but it doesn't mention the latest release is not working.
To make matters slightly more confusing, the bug mentioning the Pokemons aren't showing  (#383) was closed, although no new APK was released since then - assuming the current APK as the issue solved is an easy mistake to make, if one doesn't compare the dates.
I'm not sure if github has a status like "Solved", which would probably be preferable to "Closed" in this case - "Solved" meaning the Issue has been corrected in the source code but not present in the current release, "Closed" meaning the Issue is no longer ocurring in the current release.

To further clarify the current status of the development, they seem to have solved the issue of the missing pokemon, but have found other problem(s), which is why they haven't released an updated APK. The latest Issue where you can follow this information is #421.
