### ISSUE TITLE
Cant see anything

### ISSUE THREAD

**Issue by xDaKillerx** [omkarmoghe/Pokemap#449]
Im on android mm and on cm 13

Idk why i cant see anything.

Please help

https://drive.google.com/file/d/0B5CSyTeef3SxVjVDVFJpdC11VzA/view?usp=drivesdk

**Comment by jLynx** [comment]
What is your device?

**Comment by xDaKillerx** [comment]
Note 4 . Im using cm currently. What can be the problem? . Btw can you add black background. Real black background with white text. It might work.

**Comment by jLynx** [comment]
I have no idea what is going on. it looks like it has corrupted or something. what is that 0mA badge and the white box at the bottom?

**Comment by s7092910** [comment]
Are you using stock? Any modifications installed?

**Comment by xDaKillerx** [comment]
@DarkN3ss61 Oh. The 0mA is overlay of an app for checking my charging current. Im currently charging my phone. And @s7092910 as i said on original post. Im using cm13 not samsung stock rom. It should work. Idk. Btw. Can you try make a like test app. With the black background with white text or vice versa? . Maybe one of em can fix my prob. Thank you

**Comment by s7092910** [comment]
@xDaKillerx when I mean stock, I mean stock of the OS ROM you are using. Meaning are you using any modifications to CM 13? As I know you have Root since you have CM 13 installed on a samsung phone. So you could have xposed framework installed or some other stuff installed, etc. Also do you have the google play store and play services installed? And are they up to date?

Also I should point out that if that screenshot you posted is 100% correct, that means that changing the background, won't fix your problem.

**Comment by xDaKillerx** [comment]
@s7092910 nah its clean cm13 . Xposed only for youtube adaway

**Comment by s7092910** [comment]
@xDaKillerx But do you have google play store and play services installed and are they up to date?

**Comment by hqtrung** [comment]
Xiaomi mi 5 stock miui 8, the app used to work but after update,  it keeps report connection error.  Updated to 1.1.6 can not fix.  Uninstalled with clear cache and data didn't bring catpcha again and didn't work either.

**Comment by jLynx** [comment]
Please reopen if problem still exists
