### ISSUE TITLE
not search pokemon

### ISSUE THREAD

**Issue by rawatrob** [omkarmoghe/Pokemap#467]
I got an issue in code,  .apk is working fine  but I have check the code and run it on same devices then didn't search the pokemon.. so can you help..

**Comment by luannpeixe** [comment]
Me too, in my case it is a little different. It never worked for me.

**Comment by jLynx** [comment]
How long ago did it stop working?

**Comment by luannpeixe** [comment]
I downloaded this current version, configured, compiled and executed and no longer display pokémon, nothing. Do not run the app for me.

**Comment by luannpeixe** [comment]
up

**Comment by s7092910** [comment]
@luannpeixe are you downloading the source code or the apk from the site?

**Comment by luannpeixe** [comment]
@s7092910 source code...

**Comment by s7092910** [comment]
We have gone closed source quite some time ago(it is explained why in the readme) and the source code on here besides the string.xml hasn't been updated since Niantic added the unknown6 check. So if you want the source code to work. You will have to modify it yourself as the team is only supporting the closed source work.

**Comment by s7092910** [comment]
If you want a working version, I suggest you click the link in the readme to download the apk
