### ISSUE TITLE
Write Background Service to Utilize PokeGO API 

### ISSUE THREAD

**Issue by comann** [omkarmoghe/Pokemap#49]
The pokegoAPI-Java is not built for android in the sense of being aware to not make web calls on the main thread. This will need to be placed in a background service  exector service, or thread, or some other mechanism.

**Comment by jmrapp1** [comment]
We need to use `AsyncTask`s, this is what they are specifically meant for.

**Comment by s7092910** [comment]
@jmrapp1 `AsyncTask` would probably not be the best for this. Probably would be the worst. A `IntentService` or a `ThreadPool` might be the best option. But we will have to take a look at which option allows us to bundle calls to the pokemongo servers. Probably the Intent Service would be best. But looking at the PokeGO Api, it seems to not handle multi threading well with using as little memory as possible. Since for each thread you need to have a PokemonGo object to do a single call at a time for each location.

**Comment by CanOrhan** [comment]
@comann Doesn't the pokegoAPI use OKHttp, which internally Executors? Maybe I don't understand the issue. Could you show some code that is/will be problematic?

**Comment by s7092910** [comment]
@CanOrhan While yes the pokegoAPI does use OKHttp, it doesn't do it in async from the looks of it. But it does seem like it does do a batch request for the area. Which I'm not too sure about that. I could be wrong.

**Comment by k0mat** [comment]
have you considered using robospice?

**Comment by comann** [comment]
This has been started and is in PR #65
