### ISSUE TITLE
radius scan

### ISSUE THREAD

**Issue by Animehq** [omkarmoghe/Pokemap#92]
hey,

i'm looking for change the radius of the pokemon scan but i don't find the localisation , i see we can change the radius of the views MapWrapperFragment but nothing in controllers or model (or i'm looking for in wrong localisation ^^)

**Comment by mwillems1994** [comment]
Im exploring this as well, as far as i can see, (and note, this is just wild guess.) they send a location to the api, which has a default radius, it makes sense because in the pokemon go app, you can only see which pokemon are in your nearby radius. My guess is that they explored this weakness. So to get a higher radius, you should (and again, just a wild guess) define a searching grid and for each grid send a request to get the pokemon back.

**Comment by Animehq** [comment]
ok think i'm working on it now :)

**Comment by mwillems1994** [comment]
Let me know when you've got something, don't have the time to test it now.

**Comment by s7092910** [comment]
They already have a grid search in the api. That is current what it does. The problem is I don't think that setting the width of the search grid is public.

**Comment by Ilya-Gazman** [comment]
The radius is just fine, take a look at the last update from aaaaaa. They perform multiple searches around you in different locations. They added new toggle on the map that allows you to mark the search area
